name: WS_Tests

on:
  pull_request:
    types: [opened, reopened]
    branches: [develop]

jobs:
  WS_Tests:
    if:  startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    startegy:
      matrix:
        node-version: [14.X, 16.X]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test
      - run: npm run test:coverage > coverage.txt
      - name: upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.txt