name: Matrix

on: workflow_dispatch

jobs:
  Matrix_fruits:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        FRUITS: [pomme, banane, poire, orange]
        NOMS: [Geralt, Link, Tarnished]


    steps:
      run: echo "$NOMS mange une $FRUITS !"
        with:
          FRUITS: ${{ matrix.noms }}
          NOMS: ${{ matrix.fruits }}
